export const topProduct = [
  {
    id: 1,
    name: "Healthy Nutmix, 200g Pack",
    category: "Driedfruit",
    price_new: 42.0,
    price_old: 45.0,
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/10_1.jpg",
    isTrending: true,
  },
  {
    id: 2,
    name: "Ginger - Organic",
    category: "Vegetables",
    price_new: 62.0,
    price_old: 65.0,
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/11_1.jpg",
    isTrending: true,
  },
  {
    id: 3,
    name: "Lemon - Seedless",
    category: "Vegetables",
    price_new: 42.0,
    price_old: 45.0,
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/19_1.jpg",
    isTrending: true,
  },
  {
    id: 4,
    name: "Fresh Lichi",
    category: "Fruits",
    price_new: 10.0,
    price_old: 11.0,
    quantity: "500 g",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/25_1.jpg",
    link: "/product-left-sidebar",
    isTrending: true,
  },
  {
    id: 5,
    name: "Berry & Graps Mix Snack",
    category: "Driedfruit",
    price_new: 52.0,
    price_old: 56.0,
    quantity: "1 pcs",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/5_1.jpg",
    link: "/product-left-sidebar",
    isTrending: true,
  },
  {
    id: 6,
    name: "Fruits",
    category: "Pineapple",
    price_new: 20.0,
    price_old: 30.0,
    quantity: "12 pcs",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/29_1.jpg",
    link: "/product-left-sidebar",
    isTrending: true,
  },
  {
    id: 7,
    name: "Ginger - Organic",
    category: "Vegetables",
    price_new: 62.0,
    price_old: 65.0,
    quantity: "1 kg",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/17_1.jpg",
    link: "/product-left-sidebar",
    isTopRated: true,
  },
  {
    id: 8,
    name: "Dates Value Pouch",
    category: "Driedfruit",
    price_new: 56.0,
    price_old: 78.0,
    quantity: "3 pcs",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/2_2.jpg",
    link: "/product-left-sidebar",
    isTopRated: true,
  },
  {
    id: 9,
    name: "Blue Berry",
    category: "Fruits",
    price_new: 25.0,
    price_old: 30.0,
    quantity: "250 g",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/23_1.jpg",
    link: "/product-left-sidebar",
    isTopRated: true,
  },
  {
    id: 10,
    name: "Onion - Hybrid",
    category: "Vegetables",
    price_new: 20.0,
    price_old: 30.0,
    quantity: "12 pcs",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/13_1.jpg",
    link: "/product-left-sidebar",
    isTopRated: true,
  },
  {
    id: 11,
    name: "Potato",
    category: "Vegetables",
    price_new: 50.0,
    price_old: 55.0,
    quantity: "2 pack",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/12_1.jpg",
    link: "/product-left-sidebar",
    isTopRated: true,
  },
  {
    id: 12,
    name: "Mango - Kesar",
    category: "Fruits",
    price_new: 52.0,
    price_old: 55.0,
    quantity: "1 pcs",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/28_1.jpg",
    link: "/product-left-sidebar",
    isTopRated: true,
  },
  {
    id: 13,
    name: "Californian Almonds Value Pack",
    category: "Driedfruit",
    price_new: 25.0,
    price_old: 30.0,
    quantity: "250 g",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/3_1.jpg",
    link: "/product-left-sidebar",
    isTopSelling: true,
  },
  {
    id: 14,
    name: "Onion - Hybrid",
    category: "Vegetables",
    price_new: 20.0,
    price_old: 30.0,
    quantity: "12 pcs",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/13_1.jpg",
    link: "/product-left-sidebar",
    isTopSelling: true,
  },
  {
    id: 15,
    name: "Berry & Graps Mix Snack",
    category: "Driedfruit",
    price_new: 52.0,
    price_old: 55.0,
    quantity: "1 pcs",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/5_1.jpg",
    link: "/product-left-sidebar",
    isTopSelling: true,
  },
  {
    id: 16,
    name: "Lemon - Seedless",
    category: "Vegetables",
    price_new: 42.0,
    price_old: 45.0,
    quantity: "5 kg",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/18_1.jpg",
    link: "/product-left-sidebar",
    isTopSelling: true,
  },
  {
    id: 17,
    name: "Mango - Kesar",
    category: "Fruits",
    price_new: 62.0,
    price_old: 65.0,
    quantity: "1 kg",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/28_1.jpg",
    link: "/product-left-sidebar",
    isTopSelling: true,
  },
  {
    id: 18,
    name: "Mixed Nuts & Almonds Dry Fruits",
    category: "Driedfruit",
    price_new: 10.0,
    price_old: 11.0,
    quantity: "500 g",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/7_2.jpg",
    link: "/product-left-sidebar",
    isTopSelling: true,
  },
  {
    id: 19,
    name: "Mixed Nuts & Almonds Dry Fruits",
    category: "Driedfruit",
    price_new: 10.0,
    price_old: 11.0,
    quantity: "500 g",
    image:
      "https://grabit-react-next.maraviyainfotech.com/assets/img/product-images/7_2.jpg",
    link: "/product-left-sidebar",
    isTopSelling: true,
  },
];
